server:
  port: 9090

spring:
#    alicloud:
#      access-key: LTAI5tEDLJuJj6Mjb7MhpRZ9
#      secret-key: ZFjmPIHZWUO8w6FcK83CWvTIreqKLQ
#      sms:
#        host: https://dfsns.market.alicloudapi.com
#        path: /data/send_sms
#        method: POST
#        appCode: 51070d83172c4851a730541e1de330da
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wj?serverTimezone=GMT%2b8
    username: root
    password: root
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
#  cloud:
#    alicloud:
#      access-key: LTAI5tEDLJuJj6Mjb7MhpRZ9
#      secret-key: ZFjmPIHZWUO8w6FcK83CWvTIreqKLQ
#      oss:
#        endpoint: oss-cn-chengdu.aliyuncs.com
#        bucket: wangjiang-mall
mybatis:
  mapper-locations: classpath:mapper/*.xml  #扫描所有mybatis的xml文件
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: E:\bs\bs\mybs\pure-design-copy\flie
