server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wj?serverTimezone=GMT%2b8
    username: root
    password: root
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
mybatis:
  mapper-locations: classpath:mapper/*.xml  #扫描所有mybatis的xml文件
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: E:\bs\bs\mybs\pure-design-copy\flie
